# Generated by Django 2.2.2 on 2019-06-18 11:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=128)),
                ('address', models.CharField(max_length=256)),
                ('dateCreate', models.DateField(auto_now_add=True)),
                ('dateUpdate', models.DateField(auto_now=True)),
                ('createBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_create_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
                'unique_together': {('phone', 'email')},
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateQuote', models.DateField(default=datetime.date.today)),
                ('taxAssess', models.FileField(null=True, upload_to=projects.models.Quote.get_taxassess_upload_path)),
                ('powerBill', models.FileField(null=True, upload_to=projects.models.Quote.get_powerbill_upload_path)),
                ('cncilRate', models.FileField(null=True, upload_to=projects.models.Quote.get_councilrate_upload_path)),
                ('nearMap', models.FileField(null=True, upload_to=projects.models.Quote.get_nearmap_upload_path)),
                ('quoteFile', models.FileField(null=True, upload_to=projects.models.Quote.get_quote_upload_path)),
                ('dateCreate', models.DateField(auto_now_add=True)),
                ('dateUpdate', models.DateField(auto_now=True)),
                ('createBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote_create_by_user', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote', to='projects.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Paperwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datePaper', models.DateField(default=datetime.date.today)),
                ('ewrFile', models.FileField(null=True, upload_to=projects.models.Paperwork.get_ewrfile_upload_path)),
                ('pvFile', models.FileField(null=True, upload_to=projects.models.Paperwork.get_pvfile_upload_path)),
                ('invoiceFile', models.FileField(null=True, upload_to=projects.models.Paperwork.get_invoicefile_upload_path)),
                ('dateCreate', models.DateField(auto_now_add=True)),
                ('dateUpdate', models.DateField(auto_now=True)),
                ('createBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paperwork_create_by_user', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paperwork', to='projects.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateInstall', models.DateField(default=datetime.date.today)),
                ('installer', models.CharField(max_length=256)),
                ('inspectFile', models.FileField(null=True, upload_to=projects.models.Installation.get_inspectfile_upload_path)),
                ('installFile', models.FileField(null=True, upload_to=projects.models.Installation.get_installfile_upload_path)),
                ('dateCreate', models.DateField(auto_now_add=True)),
                ('dateUpdate', models.DateField(auto_now=True)),
                ('createBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installation_create_by_user', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installation', to='projects.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateApply', models.DateField(default=datetime.date.today)),
                ('vicApprove', models.FileField(null=True, upload_to=projects.models.Application.get_vicapproval_upload_path)),
                ('dateCreate', models.DateField(auto_now_add=True)),
                ('dateUpdate', models.DateField(auto_now=True)),
                ('createBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_create_by_user', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='projects.Customer')),
            ],
        ),
    ]
