# Generated by Django 2.2.2 on 2019-06-18 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='quote',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='app_for_quote', to='projects.Quote'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='installation',
            name='application',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='install_for_app', to='projects.Application'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paperwork',
            name='install',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pw_for_install', to='projects.Installation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='createBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='app_create_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_for_customer', to='projects.Customer'),
        ),
        migrations.AlterField(
            model_name='installation',
            name='createBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='install_create_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='installation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='install_for_customer', to='projects.Customer'),
        ),
        migrations.AlterField(
            model_name='paperwork',
            name='createBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pw_create_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paperwork',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pw_for_customer', to='projects.Customer'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_for_customer', to='projects.Customer'),
        ),
    ]
