# Generated by Django 2.2.2 on 2019-06-18 12:25

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190618_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='vicApprove',
            field=models.FileField(blank=True, default=2, upload_to=projects.models.Application.get_vicapproval_upload_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='installation',
            name='inspectFile',
            field=models.FileField(blank=True, upload_to=projects.models.Installation.get_inspectfile_upload_path),
        ),
        migrations.AlterField(
            model_name='installation',
            name='installFile',
            field=models.FileField(blank=True, upload_to=projects.models.Installation.get_installfile_upload_path),
        ),
        migrations.AlterField(
            model_name='paperwork',
            name='ewrFile',
            field=models.FileField(blank=True, upload_to=projects.models.Paperwork.get_ewrfile_upload_path),
        ),
        migrations.AlterField(
            model_name='paperwork',
            name='invoiceFile',
            field=models.FileField(blank=True, upload_to=projects.models.Paperwork.get_invoicefile_upload_path),
        ),
        migrations.AlterField(
            model_name='paperwork',
            name='pvFile',
            field=models.FileField(blank=True, upload_to=projects.models.Paperwork.get_pvfile_upload_path),
        ),
        migrations.AlterField(
            model_name='quote',
            name='cncilRate',
            field=models.FileField(blank=True, upload_to=projects.models.Quote.get_councilrate_upload_path),
        ),
        migrations.AlterField(
            model_name='quote',
            name='nearMap',
            field=models.FileField(blank=True, upload_to=projects.models.Quote.get_nearmap_upload_path),
        ),
        migrations.AlterField(
            model_name='quote',
            name='powerBill',
            field=models.FileField(blank=True, upload_to=projects.models.Quote.get_powerbill_upload_path),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quoteFile',
            field=models.FileField(blank=True, upload_to=projects.models.Quote.get_quote_upload_path),
        ),
        migrations.AlterField(
            model_name='quote',
            name='taxAssess',
            field=models.FileField(blank=True, upload_to=projects.models.Quote.get_taxassess_upload_path),
        ),
    ]
