# Generated by Django 2.2.2 on 2019-06-19 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20190618_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='quote',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='app_for_quote', to='projects.Quote'),
        ),
        migrations.AlterField(
            model_name='installation',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='install_for_app', to='projects.Application'),
        ),
        migrations.AlterField(
            model_name='paperwork',
            name='install',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pw_for_install', to='projects.Installation'),
        ),
    ]
