# Generated by Django 2.2.2 on 2019-06-21 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20190619_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='createBy',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_create_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
