# Generated by Django 2.2.2 on 2019-06-27 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20190622_0825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name_plural': '3. Application'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name_plural': '1. Customer'},
        ),
        migrations.AlterModelOptions(
            name='installation',
            options={'verbose_name_plural': '4. Installation'},
        ),
        migrations.AlterModelOptions(
            name='paperwork',
            options={'verbose_name_plural': '5. Paperwork'},
        ),
        migrations.AlterModelOptions(
            name='quote',
            options={'verbose_name_plural': '2. Quote'},
        ),
        migrations.AlterField(
            model_name='application',
            name='createBy',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='app_create_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='installation',
            name='createBy',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='install_create_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paperwork',
            name='createBy',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pw_create_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quote',
            name='createBy',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quote_create_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
