# Generated by Django 2.2.2 on 2019-07-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20190627_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('established_on', models.DateTimeField(verbose_name='date established')),
                ('employee_count', models.IntegerField()),
            ],
        ),
    ]
