# Generated by Django 2.2.2 on 2019-07-22 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
