# Generated by Django 2.2.2 on 2019-08-24 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_delete_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cx_status',
            field=models.CharField(choices=[('new', 'New'), ('info ready', 'Info Ready'), ('quote ready', 'Quote Ready'), ('installation ready', 'Installation Ready'), ('paperwork ready', 'Paperwork Ready')], default='new', max_length=16),
        ),
        migrations.AddField(
            model_name='customer',
            name='cx_type',
            field=models.CharField(choices=[('walkin', 'Walkin'), ('wholesale', 'Wholesale'), ('group order', 'Group Order')], default='walkin', max_length=32),
        ),
        migrations.AlterField(
            model_name='application',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='app_for_customer', to='projects.Customer'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(db_index=True, max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='installation',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='install_for_customer', to='projects.Customer'),
        ),
        migrations.AlterField(
            model_name='paperwork',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pw_for_customer', to='projects.Customer'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quote_for_customer', to='projects.Customer'),
        ),
    ]
