# Generated by Django 2.2.2 on 2019-08-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20190824_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cx_status',
            field=models.CharField(choices=[('new', 'New'), ('info ready', 'Info Ready'), ('quote ready', 'Quote Ready'), ('installation ready', 'Installation Ready'), ('paperwork ready', 'Paperwork Ready')], default='new', max_length=16, verbose_name='Customer Status'),
        ),
    ]
