# Generated by Django 2.2.2 on 2019-08-24 12:31

import datetime
from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20190824_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='dateApply',
            field=models.DateField(default=datetime.date.today, verbose_name='Date Applied'),
        ),
        migrations.AlterField(
            model_name='application',
            name='dateCreate',
            field=models.DateField(auto_now_add=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='application',
            name='dateUpdate',
            field=models.DateField(auto_now=True, verbose_name='Date Updated'),
        ),
        migrations.AlterField(
            model_name='application',
            name='vicApprove',
            field=models.FileField(blank=True, upload_to=projects.models.Application.get_vicapproval_upload_path, verbose_name='VIC Approval'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cx_type',
            field=models.CharField(choices=[('walkin', 'Walkin'), ('wholesale', 'Wholesale'), ('group order', 'Group Order')], default='walkin', max_length=32, verbose_name='Customer Type'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dateCreate',
            field=models.DateField(auto_now_add=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dateUpdate',
            field=models.DateField(auto_now=True, verbose_name='Date Updated'),
        ),
        migrations.AlterField(
            model_name='paperwork',
            name='dateCreate',
            field=models.DateField(auto_now_add=True, verbose_name='Date Invoiced'),
        ),
        migrations.AlterField(
            model_name='paperwork',
            name='datePaper',
            field=models.DateField(default=datetime.date.today, verbose_name='Date Completed'),
        ),
        migrations.AlterField(
            model_name='paperwork',
            name='dateUpdate',
            field=models.DateField(auto_now=True, verbose_name='Date Updated'),
        ),
        migrations.AlterField(
            model_name='paperwork',
            name='ewrFile',
            field=models.FileField(blank=True, upload_to=projects.models.Paperwork.get_ewrfile_upload_path, verbose_name='EWR File'),
        ),
        migrations.AlterField(
            model_name='paperwork',
            name='invoiceFile',
            field=models.FileField(blank=True, upload_to=projects.models.Paperwork.get_invoicefile_upload_path, verbose_name='Invoice'),
        ),
        migrations.AlterField(
            model_name='paperwork',
            name='pvFile',
            field=models.FileField(blank=True, upload_to=projects.models.Paperwork.get_pvfile_upload_path, verbose_name='PV File'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='cncilRate',
            field=models.FileField(blank=True, upload_to=projects.models.Quote.get_councilrate_upload_path, verbose_name='Council Rate'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='dateCreate',
            field=models.DateField(auto_now_add=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='dateQuote',
            field=models.DateField(default=datetime.date.today, verbose_name='Date Quoted'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='dateUpdate',
            field=models.DateField(auto_now=True, verbose_name='Date Updated'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='nearMap',
            field=models.FileField(blank=True, upload_to=projects.models.Quote.get_nearmap_upload_path, verbose_name='Near map'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='powerBill',
            field=models.FileField(blank=True, upload_to=projects.models.Quote.get_powerbill_upload_path, verbose_name='Power Bill'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quoteFile',
            field=models.FileField(blank=True, upload_to=projects.models.Quote.get_quote_upload_path, verbose_name='Quote Document'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='taxAssess',
            field=models.FileField(blank=True, upload_to=projects.models.Quote.get_taxassess_upload_path, verbose_name='Tax Assessment'),
        ),
    ]
