# Generated by Django 2.2.2 on 2019-08-24 12:48

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20190824_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='nearMap',
            field=models.FileField(blank=True, upload_to=projects.models.Quote.get_nearmap_upload_path, verbose_name='Near Map'),
        ),
    ]
