# Generated by Django 2.2.2 on 2019-08-25 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0013_auto_20190824_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='approved_by',
            field=models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quote',
            name='date_approved',
            field=models.DateField(auto_now=True, verbose_name='Date Approved'),
        ),
        migrations.AddField(
            model_name='quote',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
    ]
