# Generated by Django 2.2.2 on 2019-08-25 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20190825_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='approved_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quote',
            name='date_approved',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Approved'),
        ),
    ]
