# Generated by Django 2.2.2 on 2019-08-25 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0015_auto_20190825_1559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name_plural': '4. Application'},
        ),
        migrations.AlterModelOptions(
            name='installation',
            options={'verbose_name_plural': '5. Installation'},
        ),
        migrations.AlterModelOptions(
            name='paperwork',
            options={'verbose_name_plural': '6. Paperwork'},
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isApproved', models.BooleanField(default=False, verbose_name='Approved')),
                ('dateApproved', models.DateTimeField(auto_now=True, verbose_name='Date Approved')),
                ('ApprovedBy', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_by_user', to=settings.AUTH_USER_MODEL)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval_for_customer', to='projects.Customer')),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval_for_quote', to='projects.Quote')),
            ],
            options={
                'verbose_name_plural': '3. Approval',
            },
        ),
    ]
