# Generated by Django 2.2.2 on 2019-08-26 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0016_auto_20190825_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval',
            name='ApprovedBy',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='date_approved',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='approval',
            name='approvedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
